#!/usr/bin/env bash
set -euo pipefail

export PATH="/usr/bin:/bin:$PATH"

repo_root=$(git rev-parse --show-toplevel)
missing_headers=0

header_cpp='// Loki, a UCI-compliant chess playing software
// Copyright (C) 2021  Niels Abildskov (https://github.com/BimmerBass)
//
// Loki is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Loki is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//'

header_py='# Loki, a UCI-compliant chess playing software
# Copyright (C) 2021  Niels Abildskov (https://github.com/BimmerBass)
#
# Loki is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Loki is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#'

emit_header() {
    header=$1
    line_ending=$2

    while IFS= read -r line; do
        printf '%s%s' "$line" "$line_ending"
    done <<< "$header"
    printf '%s' "$line_ending"
}

insert_header() {
    file=$1
    header=$2

    if [ "${LOKI_LICENSE_HOOK_CHECK_ONLY:-}" = "1" ]; then
        printf 'missing license header: %s\n' "${file#$repo_root/}"
        missing_headers=1
        return
    fi

    tmp_file="${file}.license.$$"
    line_ending=$'\n'
    if grep -q $'\r$' "$file"; then
        line_ending=$'\r\n'
    fi

    if [[ "$file" == *.py ]] && head -n 1 "$file" | grep -q '^#!'; then
        head -n 1 "$file" > "$tmp_file"
        printf '%s' "$line_ending" >> "$tmp_file"
        emit_header "$header" "$line_ending" >> "$tmp_file"
        tail -n +2 "$file" >> "$tmp_file"
    else
        emit_header "$header" "$line_ending" > "$tmp_file"
        cat "$file" >> "$tmp_file"
    fi
    mv "$tmp_file" "$file"
    git add -- "$file"
}

check_file() {
    file=$1

    case "$file" in
        *.c|*.cc|*.cpp|*.cxx|*.h|*.hh|*.hpp|*.hxx)
            ;;
        *.py)
            ;;
        *)
            return
            ;;
    esac

    abs_file="$repo_root/$file"
    [ -f "$abs_file" ] || return

    if grep -q 'Copyright (C) 2021  Niels Abildskov' "$abs_file"; then
        return
    fi

    case "$file" in
        *.py)
            insert_header "$abs_file" "$header_py"
            ;;
        *)
            insert_header "$abs_file" "$header_cpp"
            ;;
    esac
}

while IFS= read -r -d '' file; do
    check_file "$file"
done < <(
    git ls-files -z -- \
        '*.c' '*.cc' '*.cpp' '*.cxx' \
        '*.h' '*.hh' '*.hpp' '*.hxx' \
        '*.py' \
        ':!Loki/__gitversion_autogen.hpp'
)

exit "$missing_headers"
