#include "pch.hpp"
#include "mocks/game_state_builder_mock.hpp"
#include "Loki/position/game_state.hpp"
#include "io/fen_reader.hpp"

namespace position_tests
{
	using namespace loki::position;
	using namespace ::testing;
#pragma region from_fen
	TEST(game_state_tests, test_fen_empty)
	{
		game_state_builder_mock builder;
		io::game_state_builder actual_builder;
		EXPECT_CALL(builder, piece_placements).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::piece_placements));
		EXPECT_CALL(builder, side_to_move).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::side_to_move));
		EXPECT_CALL(builder, castling_ability).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::castling_ability));
		EXPECT_CALL(builder, en_passant_square).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::en_passant_square));
		EXPECT_CALL(builder, halfmove_clock).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::halfmove_clock));
		EXPECT_CALL(builder, fullmove_clock).Times(0).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::fullmove_clock));
		EXPECT_THROW(game_state::from_builder(&builder, ""), io::game_state_builder::fen_parsing_error);
	}

	// Can't get this test to work...
	/*
	TEST(game_state_tests, test_fen_nonempty)
	{
		game_state_builder_mock builder;
		io::game_state_builder actual_builder;
		EXPECT_CALL(builder, piece_placements).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::piece_placements));
		EXPECT_CALL(builder, side_to_move).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::side_to_move));
		EXPECT_CALL(builder, castling_ability).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::castling_ability));
		EXPECT_CALL(builder, en_passant_square).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::en_passant_square));
		EXPECT_CALL(builder, halfmove_clock).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::halfmove_clock));
		EXPECT_CALL(builder, fullmove_clock).Times(1).WillRepeatedly(Invoke(&actual_builder, &io::game_state_builder::fullmove_clock));
		game_state::from_builder(&builder, loki::START_FEN);
		EXPECT_NO_THROW(game_state::from_builder(&builder, loki::START_FEN));
	}*/
#pragma endregion
#pragma region to_fen
	using namespace loki;
	using namespace loki::position;
	using namespace loki::position::io;

	class fen_string_builder_ctor_test :
		public ::testing::Test,
		public io_tests::fen_reader
	{};

	// Assuming the correctness of from_fen we will simply check that a FEN is "intact" when being read into a game_state instance and being re-generated by to_fen
	TEST_F(fen_string_builder_ctor_test, test_to_fen)
	{
		for (auto& test_case : fens)
		{
			auto gs = game_state::from_fen(test_case.fen);
			auto fen = game_state::to_fen(gs);
			EXPECT_EQ(fen, test_case.fen);
		}
	}
#pragma endregion
#pragma region get_piece
	TEST(game_state_test, get_piece_empty_sq)
	{
		side s = WHITE;
		game_state gs;
		std::fill_n(gs.piece_placements[WHITE], NUM_SQUARES, NO_PIECE);
		std::fill_n(gs.piece_placements[BLACK], NUM_SQUARES, NO_PIECE);

		EXPECT_EQ(gs.get_piece(A1, &s), NO_PIECE);
		EXPECT_EQ(s, NUM_SIDES);
	}
	TEST(game_state_test, get_piece_white)
	{
		side s = WHITE;
		game_state gs;
		std::fill_n(gs.piece_placements[WHITE], NUM_SQUARES, NO_PIECE);
		std::fill_n(gs.piece_placements[BLACK], NUM_SQUARES, NO_PIECE);

		gs.piece_placements[WHITE][B7] = KNIGHT;

		EXPECT_EQ(gs.get_piece(B7, &s), KNIGHT);
		EXPECT_EQ(s, WHITE);
	}
	TEST(game_state_test, get_piece_black)
	{
		side s = WHITE;
		game_state gs;
		std::fill_n(gs.piece_placements[WHITE], NUM_SQUARES, NO_PIECE);
		std::fill_n(gs.piece_placements[BLACK], NUM_SQUARES, NO_PIECE);

		gs.piece_placements[BLACK][F6] = QUEEN;

		EXPECT_EQ(gs.get_piece(F6, &s), QUEEN);
		EXPECT_EQ(s, BLACK);
	}
	TEST(game_state_test, get_piece_both_throws)
	{
		side s = WHITE;
		game_state gs;
		std::fill_n(gs.piece_placements[WHITE], NUM_SQUARES, NO_PIECE);
		std::fill_n(gs.piece_placements[BLACK], NUM_SQUARES, NO_PIECE);

		gs.piece_placements[BLACK][F6] = QUEEN;
		gs.piece_placements[WHITE][F6] = KING;

		ASSERT_THROW(gs.get_piece(F6, &s), loki_exception);
	}

#pragma endregion
}