#ifndef GENERATE_H
#define GENERATE_H
#include <random>
#include <vector>

#include "../search.h"
#include "../lnn/network.h"
#include "../lnn/trainer/data.h"


// Append one vector to another
template<typename T>
void vector_append(std::vector<T>& v1, const std::vector<T>& v2) {

    v1.reserve(v1.size() + v2.size());
    for (size_t i = 0; i < v2.size(); i++) {
        v1.push_back(v2[i]);
    }
}


namespace DataGeneration {
    // The number of threads to use.
    constexpr int THREADS = 8;
    static_assert(THREADS >= 1);

    // The maximal batch size to use for writing incrementally.
    constexpr size_t MAX_BATCH_SIZE = 5000000;
    static_assert(MAX_BATCH_SIZE > 0);

    // Defaults for data generation games
    constexpr int DEFAULT_DEPTH = 5;
    constexpr size_t DEFAULT_POSITION_COUNT = 100000000; // 100M
    constexpr bool USE_DRAWS_DEFAULT = true;
    constexpr int DEFAULT_EVAL_LIMIT = MATE - 1;
    constexpr bool RANDOM_MOVER_DEFAULT = false;
    constexpr int FIRST_RANDOM_MOVES_DEFAULT = 4;

    // Random number generator.
    static std::mt19937_64 rng(0x1234);


    // The selfplay namespace uses self-play to generate positions.
    // Note: It is currently suffering from some run-time memory corruption issues.
    namespace SelfPlay {

        // Different game results.
        enum G_RESULT :int { NOT_DONE = 0, WHITE_WIN = 1, BLACK_WIN = 2, DRAW = 3 };

        // This struct holds all data that represents one position.
        struct SavedBoard {
            // Board state
            Bitboard pieces[6][2] = { {0} };
            SIDE stm = WHITE;
            int en_passant = NO_SQ;
            int castling_rights = 0;
            int move50 = 0;

            // Score
            int score = 0;

            // Game result. 1: White win, 0.5: draw, 0: black win.
            double game_result = 0;

            void setup(const GameState_t* pos, int evaluation);

            SavedBoard();
            SavedBoard(const SavedBoard& sb);
        };



        // This class is responsible for playing a predetermined number of games on one thread.
        // Each thread will get their own
        class Arbiter {
        public:
            Arbiter(int _depth = DEFAULT_DEPTH, size_t _positions = DEFAULT_POSITION_COUNT,
                bool _draws = USE_DRAWS_DEFAULT, int _eval_limit = DEFAULT_EVAL_LIMIT,
                bool _random = RANDOM_MOVER_DEFAULT, int _first_random = FIRST_RANDOM_MOVES_DEFAULT, bool _vb = false);
            ~Arbiter();

            // Runs the specified number of games.
            void run();

        private:
            // Hyper-parameters for the generation of the data
            const int depth;
            const size_t position_count;
            const bool use_draws;
            const int eval_limit;
            const bool random_mover;
            const int first_random_moves;
            const bool verbose; // For output in play_game

            SearchThread_t* searcher;

            // Play one game.
            void play_game();

            // Prepare the searcher object to do a search.
            void prepare_search();

            // Gets all legal moves for the position.
            MoveList legal_moves();

            // Check if the game has ended.
            G_RESULT game_ended();

            // Holds all positions that we have reached.
            // Note: Ealy opening (<= move 3) and checkmate/stalemate positions are left out.
            std::vector<SavedBoard> positions;
            std::vector<SavedBoard> game_positions;

        };
    }


    // The analysis namespace analyzes positions that has already been played.
    // It takes an epd file as input.
    namespace Analysis {

        void generate_network_input(const GameState_t* pos, std::array<int8_t, INPUT_SIZE>& input);

        /*        
        Each thread wil get one object of the ThreadAnalyzer class. This is responsible for analyzing a certain batch of positions.
        */
        class ThreadAnalyzer {
        public:
            ThreadAnalyzer(const std::vector<std::string>& _fens, int depth);
        };

    }


    // Parse the output EPD generated by c-chess-cli
    void parse_c_chess(std::string filepath, std::string output, size_t batch_size = 500000);
}



#endif