#ifndef GENERATE_H
#define GENERATE_H
#include <random>
#include <vector>

#include "../search.h"
#include "../lnn/network.h"
#include "../lnn/trainer/data.h"


// Append one vector to another
template<typename T>
void vector_append(std::vector<T>& v1, const std::vector<T>& v2) {

    v1.reserve(v1.size() + v2.size());
    for (size_t i = 0; i < v2.size(); i++) {
        v1.push_back(v2[i]);
    }
}


namespace DataGeneration {
    // The number of threads to use.
    constexpr int THREADS = 8;
    static_assert(THREADS >= 1);

    // The maximal batch size to use for writing incrementally.
    constexpr size_t MAX_BATCH_SIZE = 5000000;
    static_assert(MAX_BATCH_SIZE > 0);

    // Defaults for data generation games
    constexpr int DEFAULT_DEPTH = 5;
    constexpr size_t DEFAULT_POSITION_COUNT = 100000000; // 100M
    constexpr bool USE_DRAWS_DEFAULT = true;
    constexpr int DEFAULT_EVAL_LIMIT = MATE - 1;
    constexpr bool RANDOM_MOVER_DEFAULT = false;
    constexpr int FIRST_RANDOM_MOVES_DEFAULT = 4;

    // Random number generator.
    static std::mt19937_64 rng(0x1234);


    // The analysis namespace analyzes positions that has already been played.
    // It takes an epd file as input.
    namespace Analysis {

        void generate_network_input(const GameState_t* pos, std::array<int8_t, INPUT_SIZE>& input);

        /*        
        Each thread wil get one object of the ThreadAnalyzer class. This is responsible for analyzing a certain batch of positions.
        */
        class ThreadAnalyzer {
        public:
            ThreadAnalyzer(const std::vector<std::string>& _fens, int _depth, int _bound = DEFAULT_EVAL_LIMIT);
            ~ThreadAnalyzer();

            // Will analyze all positions.
            void run();

            std::vector<Data::DataEntry> generated_entries;

        private:
            std::vector<std::string> fens;
            const int depth;
            const int score_bound;

            // Used to search with the alphabeta function.
            SearchThread_t* searcher;

            // Will clear the SearchInfo and set the correct depth.
            void setup_info();

            // Will search the position and give a white-relative score.
            // Note: Will return true if the score is inside the designated bound. Otherwise it'll return false.
            bool search(std::string fen, int& score);
        };

    }


    // Parse the output EPD generated by c-chess-cli
    void parse_c_chess(std::string filepath, std::string output, size_t batch_size = 500000);
}



#endif