if(NOT DEFINED LOKI_ROOT_DIR)
  message(FATAL_ERROR "LOKI_ROOT_DIR is required")
endif()

if(NOT DEFINED LOKI_GIT_VERSION_HEADER)
  message(FATAL_ERROR "LOKI_GIT_VERSION_HEADER is required")
endif()

set(loki_git_commit "unknown")
set(loki_git_branch "unknown")

find_program(LOKI_GIT_EXECUTABLE git)
if(LOKI_GIT_EXECUTABLE)
  execute_process(
    COMMAND "${LOKI_GIT_EXECUTABLE}" rev-parse --short=8 HEAD
    WORKING_DIRECTORY "${LOKI_ROOT_DIR}"
    OUTPUT_VARIABLE loki_git_commit_output
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE loki_git_commit_result
  )
  if(loki_git_commit_result EQUAL 0 AND NOT loki_git_commit_output STREQUAL "")
    set(loki_git_commit "${loki_git_commit_output}")
  endif()

  execute_process(
    COMMAND "${LOKI_GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY "${LOKI_ROOT_DIR}"
    OUTPUT_VARIABLE loki_git_branch_output
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE loki_git_branch_result
  )
  if(loki_git_branch_result EQUAL 0 AND NOT loki_git_branch_output STREQUAL "")
    set(loki_git_branch "${loki_git_branch_output}")
  endif()
endif()

foreach(loki_git_value IN ITEMS loki_git_commit loki_git_branch)
  string(REPLACE "\\" "\\\\" ${loki_git_value} "${${loki_git_value}}")
  string(REPLACE "\"" "\\\"" ${loki_git_value} "${${loki_git_value}}")
endforeach()

string(CONCAT loki_git_version_content
  "// Auto-generated by CMake. Do not edit manually.\n"
  "#pragma once\n"
  "#define GIT_CUR_COMMIT \"${loki_git_commit}\"\n"
  "#define GIT_BRANCH \"${loki_git_branch}\"\n"
)

get_filename_component(loki_git_version_dir "${LOKI_GIT_VERSION_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${loki_git_version_dir}")

if(EXISTS "${LOKI_GIT_VERSION_HEADER}")
  file(READ "${LOKI_GIT_VERSION_HEADER}" loki_existing_git_version_content)
  if(loki_existing_git_version_content STREQUAL loki_git_version_content)
    return()
  endif()
endif()

file(WRITE "${LOKI_GIT_VERSION_HEADER}" "${loki_git_version_content}")
